# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/bi ging ghi li/project_7/project_7.runs/synth_1_copy_1/BLK_MEM_GEN_V4_3.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1_copy_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/bi ging ghi li/project_7/project_7.cache/wt} [current_project]
set_property parent.project_path {D:/bi ging ghi li/project_7/project_7.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/bi ging ghi li/project_7/project_7.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/inst.v}
  D:/Zalo/aes_core_256/blk_mem_gen_v4_3.v
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/addroundkey.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/reg32.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/t_addround.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/aes256_core.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/aes256_cu.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/aes_keyexpand_256.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/aes_transformation.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/aes256_top.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/bytemixcolumn.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/databuffer.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/databuffer_large.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/keymodule.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/keyram_128.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/mix_invmix.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/rcon.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/tb_cores.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/reg_32.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/sbox.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/shiftsub_invshiftsub.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/subbytes.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/subword.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/t_aes256_top.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/t_cores.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/wordmixcolumn.v}
  {D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/xtime.v}
  D:/Zalo/aes_core_256/reg_32.v
  D:/Zalo/aes_core_256/sbox.v
  D:/Zalo/aes_core_256/rcon.v
  D:/Zalo/aes_core_256/subword.v
  D:/Zalo/aes_core_256/wordmixcolumn.v
  D:/Zalo/aes_core_256/databuffer.v
  D:/Zalo/aes_core_256/aes_transformation.v
  D:/Zalo/aes_core_256/t_addround.v
  D:/Zalo/aes_core_256/mix_invmix.v
  D:/Zalo/aes_core_256/aes_keyexpand_256.v
  D:/Zalo/aes_core_256/aes256_core.v
  D:/Zalo/aes_core_256/keyram_128.v
  D:/Zalo/aes_core_256/aes256_top.v
  D:/Zalo/aes_core_256/reg32.v
  D:/Zalo/aes_core_256/t_aes256_top.v
  D:/Zalo/aes_core_256/keymodule.v
  D:/Zalo/aes_core_256/tb_cores.v
  D:/Zalo/aes_core_256/aes256_cu.v
  D:/Zalo/aes_core_256/addroundkey.v
  D:/Zalo/aes_core_256/bytemixcolumn.v
  D:/Zalo/aes_core_256/shiftsub_invshiftsub.v
  D:/Zalo/aes_core_256/inst.v
  D:/Zalo/aes_core_256/xtime.v
  D:/Zalo/aes_core_256/databuffer_large.v
  D:/Zalo/aes_core_256/subbytes.v
  D:/Zalo/aes_core_256/t_cores.v
}
read_verilog {{D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/blk_mem_gen_v4_3.v}}
read_edif {{D:/bi ging ghi li/project_7/project_7.srcs/sources_1/imports/aes_core_256/aes256_core.ngc}}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/bi ging ghi li/project_7/project_7.srcs/constrs_1/new/lmao.xdc}}
set_property used_in_implementation false [get_files {{D:/bi ging ghi li/project_7/project_7.srcs/constrs_1/new/lmao.xdc}}]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental {D:/bi ging ghi li/project_7/project_7.srcs/utils_1/imports/synth_1/blk_mem_gen_v4_3.dcp}
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top BLK_MEM_GEN_V4_3 -part xc7vx485tffg1761-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef BLK_MEM_GEN_V4_3.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file BLK_MEM_GEN_V4_3_utilization_synth.rpt -pb BLK_MEM_GEN_V4_3_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1_copy_1" END { }
